### ISSUE TITLE
Exceptions when the status code is 400 and the request url is invalid

### ISSUE THREAD

**Issue by hiql** [nielsbasjes/logparser#249]
Logs:
```
170.187.225.221 - - [28/Feb/2023:16:48:52 +0800] "GET :@bxss.me::80/rpb.png HTTP/1.1" 400 1160
170.187.225.221 - - [28/Feb/2023:16:48:51 +0800] "GET @bxss.me::80/rpb.png HTTP/1.1" 400 1160
170.187.225.221 - - [28/Feb/2023:16:48:51 +0800] "GET :@bxss.me/rpb.png HTTP/1.1" 400 1160

```
Exception:
```

Caused by: nl.basjes.parse.core.exceptions.DissectionFailure: Failed to parse URI >>:@bxss.me::80/rpb.png<< because of : Expected scheme name at index 0: :@bxss.me::80/rpb.png

```

Longing for help....🙏

**Comment by nielsbasjes** [comment]
I had a good look at this and I did the following:
- Problems that are "server-side" (like bad timestamp parsing) will still fail with a DissectionFailure; you should fix that.
- Problems that are "client-side" (usually hackers) will simply not return the requested fields; you cannot fix or prevent that.

**Comment by nielsbasjes** [comment]
Version 5.10.0 should fix your problem.
Please reopen if you still have issues.

**Comment by hiql** [comment]
@nielsbasjes 
You did great👍，that's what I need!
For me ,the ip and timestamp are more important than the request url, even the url is bad.
Thank you very much!!!
