### ISSUE TITLE
Parse or ignore timestap

### ISSUE THREAD

**Issue by secfree** [nielsbasjes/logparser#27]
As

> %{format}t : The time, in the form given by format, which should be in strftime(3) format. (potentially localized)

How can I parse or ingore the timestamp if it's not in `standard english format` ?

Thanks.

**Comment by nielsbasjes** [comment]
Can you provide me with an example logformat specification and a single logline so I can have a look on how to do that?
Thanks.

**Comment by nielsbasjes** [comment]
I found a simple workaround:
Before you feed the logformat to the parser replace the **`%{...}t`** in your logformat with **`%{timestamp}i`** .
You will then get the value as a `HTTP.HEADER:request.header.timestamp` which is just a textual string.

**Comment by nielsbasjes** [comment]
I documented the workaround and I created a special parsing for this field that will become part of version 2.5.
