### ISSUE TITLE
Parser breaking with 408 status code in mod_reqtimeout

### ISSUE THREAD

**Issue by diogosantana** [nielsbasjes/logparser#31]
The parser is breaking parsing mod_reqtimeout entry for 408 status code.

Example line:

`187.41.80.255 - - [05/Aug/2016:09:32:06 -0300] "-" 408 - "-" "-" 0/14`

Example LogFormat string:

`String localLogFormat = "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %T/%D";`

I will push to my repository a test case.

**Comment by nielsbasjes** [comment]
Thanks for reporting this!
I found what fails: The first line of the request is a '-' instead of something like 'GET / HTTP/1.1'

I'll have to investigate what the right solution is for this.

**Comment by nielsbasjes** [comment]
I did some more testing with this module and found more fields that would fail parsing.
I fixed those and added a new unit test to verify it all.
I just build and pushed version 2.7-SNAPSHOT to maven.
Can you please double check it now works for you too?
Thanks.

**Comment by diogosantana** [comment]
Niels, it is working here. Thanks for the fast fix.

**Comment by nielsbasjes** [comment]
Great. Thanks for reporting this.
