### ISSUE TITLE
Enhancement: Validate format & message

### ISSUE THREAD

**Issue by vn-techie** [nielsbasjes/logparser#33]
Hello,
Can I have a behavior of validating the format along with message and says valid or invalid either by true/false or true/exception manner.

Case:
1. common format & common message --> returns true
2. combined format & combine message  --> returns true
3. common format & combined message --> returns false
4. combined format & common message --> returns false
5. common format & custom message --> return false
6. combined format & custom message --> return false
etc?

Thanks,
Vn

**Comment by nielsbasjes** [comment]
This is already in the system.

If you parse a line with a parser:

- If the format and the line match then you get the parsed result.
- If the format and the line DO NOT match then you get a DissectionFailure exception.

So what you need can be written as something like this:

        try {
            parser.parse(record, logline);
            return true;
        } catch (DissectionFailure dissectionFailure) {
            return false;
        }

**Comment by vn-techie** [comment]
Hi Neil,

Yeah, i know. But, this need a log line object with annotations. I do not want to have each class definition for each format. As, the format can be anything in custom. Can i use empty object for this case?

How does this works for random input format or partial valid remaining random format cases?

**Comment by nielsbasjes** [comment]
The system has been highly optimized. If you ask for nothing it does nothing. So you need to ask for at least one simple thing in the line that must exist in the line.

So something like
class DummyRecord{
        @Field("TIME.STAMP:request.receive.time")
        public void set(String value){};
    }

and in your code:
            parser.parse(new DummyRecord(), logline);

Note that if the requested thing is missing in the logformat it check will pass because of the optimizations done in the system.

**Comment by nielsbasjes** [comment]
A relatively simple way of doing it without any edge cases is by letting the system create the regex and then try to see if it matches yourself.
I.e. something like this:

```
        ApacheHttpdLogFormatDissector httpdLogFormatDissector = new ApacheHttpdLogFormatDissector(logformat);
        httpdLogFormatDissector.prepareForRun();
        String regex = httpdLogFormatDissector.getLogFormatRegEx();

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(logline);
        if (matcher.matches()) {
          // do stuff   
        }

```

**Comment by vn-techie** [comment]
This pattern match helps. Thanks you
