### ISSUE TITLE
JodaTime fails when parsing field 'MMM' with mix of upper and lower case

### ISSUE THREAD

**Issue by kengu** [nielsbasjes/logparser#35]
Default timestamp in Common Log format is "dd/MMM/yyyy:HH:mm:dd z", where MMM={JAN,FEB,...DEC}. JodeTime will fail however, if you us captialized month, for example `30/Sep/2016:00:00:06 +0000`, where **Sep** is unrecognized by Jodatime. It seems to be expected behaviour. See http://joda-interest.219941.n2.nabble.com/JodaTime-1-5-2-DateTimeFormatter-and-case-sensitivity-td364187.html

*Fix*

Add uppercase/lowercase to fieldValue @ [master/TimeStampDissector.java:311](https://github.com/nielsbasjes/logparser/blob/master/httpdlog/httpdlog-parser/src/main/java/nl/basjes/parse/httpdlog/dissectors/TimeStampDissector.java#L311)

**Comment by nielsbasjes** [comment]
Thanks for reporting this.
Can you provide me with more details (like the LogFormat specification) when this effect occurs?
Thanks.

**Comment by nielsbasjes** [comment]
Fixed.
