### ISSUE TITLE
How to set DateTimeFormatter.Local?

### ISSUE THREAD

**Issue by pkptzx** [nielsbasjes/logparser#37]
> Exception in thread "main" nl.basjes.parse.core.exceptions.DissectionFailure: Invalid format: "28/feb/2017:03:39:40 +0800" is malformed at "feb/2017:03:39:40 +0800"

because log in server , but analyzing log in my computer ....
DateTime Local is different

**Comment by nielsbasjes** [comment]
Try changing your logformat to replace the `%t` with the appropriate `%{format}t` value.
Here you can find the supported fields: https://github.com/nielsbasjes/logparser/blob/master/httpdlog/httpdlog-parser/src/main/java/nl/basjes/parse/httpdlog/dissectors/StrfTimeStampDissector.java#L200

Looking at your example I would guess something like this: `%{%d/%b/%Y:%H:%M:%S %z}t`

**Comment by nielsbasjes** [comment]
To verify I added an extra test in the code base with this timestamp.
This works as I expect it to work:

```
    @Test
    public void testReportedSpecialTime() throws Exception {
        String logline = "28/feb/2017:03:39:40 +0800";
        String logformat = "%{%d/%b/%Y:%H:%M:%S %z}t";

        DissectorTester.create()
            .withDissector(new HttpdLogFormatDissector(logformat))
            .withInput(logline)
            .expect("TIME.EPOCH:request.receive.time.epoch", "1488224380000")
            .checkExpectations();
    }
```

I verified the result using this
https://www.epochconverter.com/timezones?q=1488224380&tz=Asia%2FHong_Kong
