### ISSUE TITLE
Why is usec_frac not translated into JodaTime?

### ISSUE THREAD

**Issue by james-woods** [nielsbasjes/logparser#43]
This line here:

https://github.com/nielsbasjes/logparser/blob/2190fc129f2c2f0813b981e9bf34d60699c9551f/httpdlog/httpdlog-parser/src/main/java/nl/basjes/parse/httpdlog/dissectors/StrfTimeStampDissector.java#L176

is commented out, but my logformat is using usec_frac - is there a reason why it's not in?

**Comment by nielsbasjes** [comment]
To be honest: I don't remember.
I think the reason was that I couldn't get it to work right.
With the 4.0 release I switched to the native time library of Java 8 and there this usec_frac is supported.

Can you check if that works for you?
Thanks.

**Comment by james-woods** [comment]
I am using version 4.0, but I narrowed down my problem so it could be that you are right and `usec_frac` works, but I am just using it wrong. I can try it with my pattern when #44 works
Thank you!
