### ISSUE TITLE
Option to call setter only when value is non-null

### ISSUE THREAD

**Issue by james-woods** [nielsbasjes/logparser#46]
I am using logparser in an Apache Beam Project. 

Apache Beam does not like null values, thus having an option to set a value only when it's non-null would be helpful. Otherwise one has to write a custom setter with a null check for every field.
It's triggered when `-` is parsed to `null`. When the variable holding this value was initialized with an empty string, it becomes `null` after deserialization.

**Comment by james-woods** [comment]
might be more a Beam issue, needs more investigation from my side

**Comment by nielsbasjes** [comment]
Seemed like a good idea anyway. So I added the option of setting a setterPolicy which indicates if Empty and Null values should be sent into the setter.

**Comment by james-woods** [comment]
Wow, this is great! Unfortunately that change might be related to #47
