### ISSUE TITLE
add name change interface

### ISSUE THREAD

**Issue by ppsnumi** [nielsbasjes/logparser#53]
Hi~

I am using logparser well.
But there is one inconvenience.

That is, if the information parsed by @Field ("PossiblePathName") is parsed as name/value, such as Map, then PossiblePathName is not useful key name.

A typical example is URL query parameter parsing.

```
@Field ("STRING:request.firstline.orifinal.uri.query.*")
public void addQuery (String name, String value) {
...
}
```

The results are shown below.

```
{
STRING:request.firstline.original.uri.query.param1 = xxxxxx,
STRING:request.firstline.original.uri.query.param2 = xxxxxx
}
```

Here, I wonder if there is a way to input the original parameter name (param1) instead of "request.firstline.original.uri.query.param1" or an interface provided separately.

Also for @Field () with multiple PossiblePathName

```
@Field ({"TIME.DATE:request.receive.time.date:paramname1"}, {"TIME.DATE:request.receive.time.time:paramname2"}}
method {
}
```
I would like to have the ability to specify name in the form of.

thanks....

**Comment by nielsbasjes** [comment]
Hi

> I wonder if there is a way to input the original parameter name (param1) instead of "request.firstline.original.uri.query.param1"

No there isn't a way to do that with the library.

You can simply do that yourself like this:

    String parameterName = name.substring(name.lastIndexOf('.')+1);

Your suggestion that you can specify the 'name' of the parameter can also be solved very easily in your own code: simply create a `Map<String,String>` to convert the provided name into the name you want.

So in both scenarios I think this is something your application code should handle.
