### ISSUE TITLE
Mapping to Java Data Types?

### ISSUE THREAD

**Issue by cgivre** [nielsbasjes/logparser#56]
HI @nielsbasjes 
Firstly, thank you very much for the logparser.  It is a very powerful library and I'm really glad that you open sourced it and continue to maintain it.  

I had a question more than an issue.  I am currently re-working Drill's use of the HTTPD reader, and need to be able to map the returned fields to Drill's data types, which largely mirror Java's data types. 

I see that logparser returns fields, most of which are strings, but many are not, such as timestamps, port numbers etc.  So here are my questions:
1.   Is there an easy way to know whether a field returns a numeric value other than hard coding it?
2.  Is there some comprehensive list of possible data types in the module?

Thanks!

**Comment by nielsbasjes** [comment]
Hi @cgivre 

The parser evolves around "Dissectors" that are capable of cutting an input String into one of more pieces. 
All inputs for Dissectors are strings and each Dissector provides information about what the various pieces can be Cast into: String, Long, Double or any combination of those.
https://github.com/nielsbasjes/logparser/blob/master/parser-core/src/main/java/nl/basjes/parse/core/Casts.java

You can ask the parser what the possible Casts are possible for a field https://github.com/nielsbasjes/logparser/blob/master/parser-core/src/main/java/nl/basjes/parse/core/Parser.java#L126

The way I made the system to work is that it will call the methods you provided ( either via annotations or via https://github.com/nielsbasjes/logparser/blob/master/parser-core/src/main/java/nl/basjes/parse/core/Parser.java#L521 ) depending on the signature of the method (does it want a String, Long or Double) and if the desired field van be provided in that form.

You can then also choose for what values the setters are actually called: https://github.com/nielsbasjes/logparser/blob/master/parser-core/src/main/java/nl/basjes/parse/core/Parser.java#L51

Does this answer your questions?

Niels

**Comment by cgivre** [comment]
@nielsbasjes 
Thanks for your response.  From other parsers I've used this seems really complicated and my concern is that the performance is taking a hit due to all the complexity.  What I was hoping for, and what usually happens in most parsers, is there some sort of API that would enable me to get back an iterable object of the fields and their respective values?

My concern is that the current implementation creates a lot of overhead which will decrease performance.

**Comment by nielsbasjes** [comment]
The reason the system is setup this way is that now 
- The system does not dissect the field that are not requested
- The system can easily be extended with additional dissectors (like I have created for Yauaa).

So you tell what you want and then the system can figure out which dissectors are needed to handle this, and then it can tell you (based on the input from the dissectors) to which of the 3 types the value can be cast.

Given the flexibility I wanted this still seems to me a pretty good solution direction.

**Comment by nielsbasjes** [comment]
@cgivre I assume you questions were answered. If not then please reopen this.
