### ISSUE TITLE
Update commons-httpclient version

### ISSUE THREAD

**Issue by vvysotskyi** [nielsbasjes/logparser#58]
`commons-httpclient` is too old and contains a lot of vulnerabilities. This library changed artifact name and is available as `org.apache.httpcomponents:httpclient`.

**Comment by nielsbasjes** [comment]
Thanks for the headsup.
I've gone over my code and updated just about all dependencies.
Funny thing is that the usage of the httpclient was so limited that after a little rewrite I could drop the dependency completely.

I've released version 5.3 so you can immediately (in an hour or so when it arrives at maven central) use it.

**Comment by vvysotskyi** [comment]
Great! Thank you for so quick fix and for making the release!
