### ISSUE TITLE
Support for custom dynamic fields

### ISSUE THREAD

**Issue by Glamdring** [nielsbasjes/logparser#63]
Log formats support additional custom fields, e.g. appended by services like CloudFlare. A cloudflare log might look like:

162.138.110.111 - - [02/Apr/2021:19:06:18 +0300] "OPTIONS /test HTTP/1.1" 204 0 "http://localhost/" "Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.86 Mobile Safari/537.36" 334b4dae3b4add48-FRA DE

This is parsed by specifying the following at the end of the format: %{CFRay}i %{CFCountry}i'

But I can't seem to obtain it (in the Java library). And though I can probably find it via getPossiblePaths, in my case these things should be configurable by end users. So is there a way to fill all fields not found on the POJO in a Map (key, value, or key-multivalue)? E.g. if the POJO define a Map<String, String>, then fill it with all unknown items

**Comment by nielsbasjes** [comment]
Can you please provide with the exact logformat for this line?
Or even better: a code fragment that shows the issue you have?

**Comment by nielsbasjes** [comment]
I reread you question and perhaps this is what you are looking for: https://github.com/nielsbasjes/logparser/blob/master/httpdlog/httpdlog-parser/src/test/java/nl/basjes/parse/httpdlog/BasicOverallTest.java#L122

Here I get all possible fields and then assign all of these fields to a setter.
Then when you run the code this setter receives all values.

Now in your scenario you may want to add a filter to only let the fields pass that start with (for example)  "HTTP.HEADER:request.header.".

Then in this setter you can put everything you receive into the Map you are looking for.

Code fragment of what I mean:

```
class MyRecord {

        private final Map<String, String> requestHeaders = new TreeMap<>();

        public void setRequestHeader(final String name, final String value) {
            requestHeaders.put(name, value);
        }

        public Map<String, String> getRequestHeaders() {
            return requestHeaders;
        }

        public void clear() {
            requestHeaders.clear();
        }
    }
```

and 

```
        Parser<MyRecord> parser = new HttpdLoglineParser<>(MyRecord.class, LOG_FORMAT);
        MyRecord         record = new MyRecord();

        List<String> paths = parser.getPossiblePaths();

        paths = paths.stream().filter(p -> p.contains("request.header.")).collect(Collectors.toList());

        parser.addParseTarget(record.getClass().getMethod("setRequestHeader", String.class, String.class), paths);

        for (String logline : LOG_LINES) {
            record.clear();
            parser.parse(record, logline);
            System.out.println(record.getRequestHeaders());
        }
```


Would that answer your question?

**Comment by nielsbasjes** [comment]
Totally other solution idea: 
I assume you have a base string and some additional optional fields that can be appended.
If you take the full logformat and remove the base "sub-string" from that.
Then put the remaining string in the parser and then you'll only have all possible fields that stem from the manual additions.
You can assign just those to a setter and store the result in a Map.

**Comment by Glamdring** [comment]
Hello,

Thanks, that works (the previous message with reflection).
